id: I2EE4ACD2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:37:02+00:00'
last_modified: '2022-06-07T16:34:32.361740+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4328
  title: བླ་བརྒྱུད་རྣམ་ཐར་དང་རྒྱན་དྲུག་ལོ་རྒྱུས་མདོར་བསྡུས་བློ་མུན་བསལ་བའི་མིག་ཐུར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0BBA:
      image_group_id: I1KG4416
      title: ''
      total_pages: 68
      order: 1
      base_file: 0BBA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
