id: P002959
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4328
  title: བླ་བརྒྱུད་རྣམ་ཐར་དང་རྒྱན་དྲུག་ལོ་རྒྱུས་མདོར་བསྡུས་བློ་མུན་བསལ་བའི་མིག་ཐུར་
  author: ''
  volumes:
    ff6d689d7ab4460ebfd4bbd0f52f9707:
      image_group_id: I1KG4416
      title: ''
      volume_number: 1
      total_pages: 68
      base_file: v001.txt
